name: Gource

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Install Gource
        run: |
          sudo apt-get update
          sudo apt-get install -y gource

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Update submodules
        run: |
          git submodule update --init --recursive

      - name: Run Bash script
        run: |
          bash script.sh

      - name: Upload video
        uses: actions/upload-artifact@v2
        with:
          name: Gource video
          path: output.mp4
